import logo from './assets/logo.png';
import dokiLogo from './assets/dokilogo.png';

const Themes = {
  default: {
    backgroundColor: 'bg-slate-950',
    contentBackgroundColor: '',
    buttonBG: 'bg-green-800',
    buttonBorder: '',
    buttonHover: 'hover:bg-green-700',
    buttonOutline: 'focus-visible:outline-green-800',
    buttonText: 'text-white',
    inputFocus: 'focus-within:ring-indigo-600',
    textColor: 'text-white',
    errorText: 'text-red-600',
    svgFill: 'fill-red-500',
    bgImage: '',
    visibility: '',
  },
  bm: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-smoke bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  death: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-deathBG bg-contain bg-center  bg-no-repeat  ',
    visibility: '',
  },
  otfgk: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-otfgkBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  throne: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-throneBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  bbab: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-blue-700',
    buttonBorder: 'border-2 border-blue-500',
    buttonHover: 'hover:bg-blue-500',
    buttonOutline: 'focus-visible:outline-blue-800',
    buttonText: 'text-black hover:text-black',
    inputFocus: 'focus-within:ring-blue-600',
    textColor: 'text-blue-600',
    errorText: 'text-red-600',
    svgFill: '',
    bgImage: 'bg-bbabBG bg-contain bg-center  bg-no-repeat  ',
    visibility: '',
  },
  theone: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-amber-200',
    buttonHover: 'hover:bg-amber-200',
    buttonOutline: 'focus-visible:outline-amber-700',
    buttonText: 'text-amber hover:text-black',
    inputFocus: 'focus-within:ring-amber-500',
    textColor: 'text-amber-500',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-theOne bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  doki: {
    logoImage: dokiLogo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-pink-200',
    buttonHover: 'hover:bg-pink-200',
    buttonOutline: 'focus-visible:outline-pink-700',
    buttonText: 'text-pink hover:text-black',
    inputFocus: 'focus-within:ring-pink-500',
    textColor: 'text-pink-500',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-dokiBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  megitsune: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-megitsuneBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  momo: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-pink-200',
    buttonHover: 'hover:bg-pink-500',
    buttonOutline: 'focus-visible:outline-pink-700',
    buttonText: 'text-pink hover:text-black',
    inputFocus: 'focus-within:ring-pink-500',
    textColor: 'text-pink-500',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-momoBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  moa: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-blue-800',
    buttonBorder: 'border-2 border-blue-800',
    buttonHover: 'hover:bg-blue-200',
    buttonOutline: 'focus-visible:outline-blue-800',
    buttonText: 'text-white hover:text-black',
    inputFocus: 'focus-within:ring-blue-600',
    textColor: 'text-blue-600',
    errorText: 'text-red-600',
    svgFill: '',
    bgImage: 'bg-moaBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  su: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-suBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
  yui: {
    logoImage: logo,
    backgroundColor: 'bg-black',
    contentBackgroundColor: 'bg-black/[.7] ',
    buttonBG: 'bg-black',
    buttonBorder: 'border-2 border-bmRed',
    buttonHover: 'hover:bg-red-700',
    buttonOutline: 'focus-visible:outline-red-800',
    buttonText: 'text-bmRed hover:text-black',
    inputFocus: 'focus-within:ring-red-600',
    textColor: 'text-red-600',
    errorText: 'text-blue-600',
    svgFill: '',
    bgImage: 'bg-yuiBG bg-cover bg-center  bg-no-repeat  ',
    visibility: '',
  },
};

export default Themes;
